### ISSUE TITLE
[q&a] more details

### ISSUE THREAD

**Issue by matttbe** [mux99/mptcp.dev#12]
Add a dropdown menu with more details: A part of what is currently in the Q&A comes from the lighttpd PR, but as a summary. Some details might be important, e.g. MPTCP is supported on macOS, but the API is different (and not easily accessible)

**Comment by matttbe** [comment]
Mmh, I see you fixed the part linked to the example I gave (MPTCP support in other OS), but this was more global: I'm not used to work with LLM tools, but here, it looks like they removed important info, e.g.
- security: link to RFC section that was present in my comment in the lighttpd PR (for the privacy, what is currently described is not saying a lot)
- performance: it doesn't explain the fact it is a good idea to enable it by default on a server, mentioning that "plain" TCP connections will continue to use TCP sockets, not going through the MPTCP layer.
- QUIC: it would be nice to keep the link to the draft for multipath: not standardized yet
- also, it would be good to add something about checks at build time: for both lighttpd and curl, there were questions about checking if MPTCP was supported at build time.

So OK to re-open it?

**Comment by mux99** [comment]
these have been added, but I am not sure if the level of details is enough
I let you(@matttbe) close this issue if so

**Comment by matttbe** [comment]
Thank you for the modifications. I will close this, the rest will be part of the review
